print("Assignment 1")
print("")
v1=float(eval(input("Enter value 1:")))
v2=float(eval(input("Enter value 2:")))
v3=float(eval(input("Enter value 3:")))
v4=float(eval(input("Enter value 4:")))
v5=float(eval(input("Enter value 5:")))
print("")
avgNum=(v1+v2+v3+v4+v5)/5
print(f"The average of the values is:={avgNum}")
print("")
print("Assignment 2")
print("")
from math import pi
r=float(eval(input("What is the radius of the circle?: ")))
print("")
print("The radius of the circle is: ",r)
print("The diameter of the circle is: ",2*r)
print("The circumference of the circle is: ",round(2*pi*r,2))
print("The area of the circle is: ",round(pi*r**2,2))
print("")
print("Assignment 3")
print("")
import math
cor_x1=float(eval(input("Enter coordinate 1 for point X: ")))
cor_x2=float(eval(input("Enter coordinate 2 for point X: ")))
cor_y1=float(eval(input("Enter coordinate 1 for point Y: ")))
cor_y2=float(eval(input("Enter coordinate 2 for point Y: ")))
d = math.sqrt((cor_x1-cor_y1)**2 + (cor_x2-cor_y2)**2)
print("The distance between point 1 and point 2 is: ",d)
print("")
print("Extra Practical")
print("")
t1=float(eval(input("Test 1: ")))
t2=float(eval(input("Test 2: ")))
t3=float(eval(input("Test 3: ")))
print("")
avgN=(t1+t2+t3)/3
print("")
print("The average of the tests is: ",avgN)
print("")
if avgN > 75 : print("Congratulations!")
else : print("Try Again")
